stages:
  - test
  - build

# ✅ Frontend directory
variables:
  FRONTEND_DIR: "frontend"

# -------------------------
# Run frontend tests
# -------------------------
test:
  stage: test
  script:
    - cd $FRONTEND_DIR
    - npm ci
    - npm run test
  tags:
    - frontend_MYJ
  only:
    - UAT-Internal-Testing2
    - UAT-Internal-Testing

# -------------------------
# Build + Deploy for TEST
# -------------------------
build_test:
  stage: build
  needs: ["test"]
  script:
    - echo "🚀 Deploying to TEST..."
    - cd $FRONTEND_DIR
    - npm install

    # ✅ Inject TEST environment variables
    # These env vars will be used by Vite during build:test
    - echo "VITE_API_URL=$VITE_TEST_API_URL" >> .env
    - echo "VITE_SOCKET_URL=$VITE_TEST_SOCKET_URL" >> .env
    - echo "VITE_CAPTCHA_BACKEND_URL=$VITE_CAPTCHA_BACKEND__TEST_URL" >> .env   # fixed ✅
    - echo "VITE_FRONTEND_API_URL=$VITE_TEST_FRONTEND_API_URL" >> .env
    - echo "VITE_CAPTCHA_SITE_KEY=$VITE_CAPTCHA_SITE_KEY" >> .env
    - echo "CAPTCHA_SECRET_KEY=$CAPTCHA_SECRET_KEY" >> .env

    # ✅ Build with TEST mode
    - npm run build:test

    # ✅ AWS Deploy (sync build artifacts to TEST bucket)
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_REGION
    - aws s3 sync dist/ s3://$S3_BUCKET_ID_2 --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID_UAT2 --paths "/*"

  tags:
    - frontend_MYJ
  artifacts:
    paths:
      - frontend/dist
  only:
    - UAT-Internal-Testing2

# -------------------------
# Build + Deploy for PROD
# -------------------------
build_prod:
  stage: build
  needs: ["test"]
  script:
    - echo "🚀 Deploying to PROD..."
    - cd $FRONTEND_DIR
    - npm install

    # ✅ Inject PROD environment variables
    - echo "VITE_API_URL=$VITE_PROD_API_URL" >> .env
    - echo "VITE_SOCKET_URL=$VITE_PROD_SOCKET_URL" >> .env
    - echo "VITE_CAPTCHA_BACKEND_URL=$VITE_PROD_CAPTCHA_BACKEND_URL" >> .env   # consistent ✅
    - echo "VITE_FRONTEND_API_URL=$VITE_PROD_FRONTEND_API_URL" >> .env
    - echo "VITE_CAPTCHA_SITE_KEY=$VITE_CAPTCHA_SITE_KEY" >> .env
    - echo "CAPTCHA_SECRET_KEY=$CAPTCHA_SECRET_KEY" >> .env

    # ✅ Build with PROD mode
    - npm run build:prod

    # ✅ AWS Deploy (sync build artifacts to PROD bucket)
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_REGION
    - aws s3 sync dist/ s3://$S3_BUCKET_ID --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID_INTERNAL --paths "/*"

  tags:
    - frontend_MYJ
  artifacts:
    paths:
      - frontend/dist
  only:
    - UAT-Internal-Testing
